# Inserts a blank line between shell prompts
add_newline = true

# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format = """$all"""

[character]       
# Replace the "❯" symbol in the prompt with "➜"
#success_symbol = "[➜](bold green) "
# error_symbol = "[➜](bold red) "
# with custom vim shape
vicmd_symbol = "[V](bold green) "

