# config file for starship prompt

# A minimal left prompt
# format = """$character"""

# Move the directory to the second line
# format="$all$directory$character"

# move the rest of the prompt to the right
# right_format = """$all"""

# Inserts a blank line between shell prompts
add_newline = true

[character]       
# Replace the "❯" symbol in the prompt with "➜"
success_symbol = "[➤](bold green)"
error_symbol = "[➤](bold red)"

# with custom vim shape
vicmd_symbol = "[V](bold green) "

[time]
time_format = "%T"
format = '[\[$time\]](italic gray) '
style = "bright-white"
disabled = true
